#!/usr/bin/env python3
"""Generates seed/seed.sql (demo data). Run: python3 seed/generate.py
Dates are written as SQLite expressions relative to "now", so the demo always looks current.
Demo logins (change or remove before going live):
  admin@gosanchari.com / GoSanchari@2026   (Admin)
  manager@gosanchari.com, priya@gosanchari.com (Sales), arjun@gosanchari.com (Sales), accounts@gosanchari.com — same password
"""
import base64, hashlib, json, os

PASSWORD = 'GoSanchari@2026'


def pw(password: str) -> str:
    salt = os.urandom(16)
    h = hashlib.pbkdf2_hmac('sha256', password.encode(), salt, 100_000, 32)
    return f"pbkdf2$100000${base64.b64encode(salt).decode()}${base64.b64encode(h).decode()}"


def q(v):
    if v is None:
        return 'NULL'
    if isinstance(v, bool):
        return '1' if v else '0'
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, (list, dict)):
        v = json.dumps(v, ensure_ascii=False)
    return "'" + str(v).replace("'", "''") + "'"


def d(days: int) -> str:
    return f"date('now', '+5 hours', '+30 minutes', '{days:+d} days')"


def ts(days: float) -> str:
    return f"strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '{days * 24:+.1f} hours')"


out = ['-- Generated by seed/generate.py — demo data for Go Sanchari', 'PRAGMA foreign_keys = OFF;']

users = [
    (1, 'admin', 'Anitha Admin', '+919000000001', 'admin@gosanchari.com'),
    (2, 'manager', 'Mathew Manager', '+919000000002', 'manager@gosanchari.com'),
    (3, 'sales', 'Priya Nair', '+919000000003', 'priya@gosanchari.com'),
    (4, 'sales', 'Arjun Menon', '+919000000004', 'arjun@gosanchari.com'),
    (5, 'accounts', 'Asha Accounts', '+919000000005', 'accounts@gosanchari.com'),
    (10, 'guest', 'Rahul Varma', '+919812345601', 'rahul@example.com'),
    (11, 'guest', 'Sneha Pillai', '+919812345602', 'sneha@example.com'),
    (12, 'guest', 'Fathima Rasheed', '+919812345603', None),
    (13, 'guest', 'David Thomas', '+919812345604', 'david@example.com'),
    (14, 'guest', 'Lakshmi Iyer', '+919812345605', None),
]
for uid, role, name, phone, email in users:
    out.append(f"INSERT INTO users (id, role, name, phone, email, password_hash, language) VALUES ({uid}, {q(role)}, {q(name)}, {q(phone)}, {q(email)}, {q(pw(PASSWORD) if role != 'guest' else None)}, {q('ml' if uid == 12 else 'en')});")
out.append("INSERT INTO staff_destinations (user_id, destination) VALUES (3, 'Munnar'), (3, 'Thekkady'), (3, 'Vagamon'), (4, 'Wayanad'), (4, 'Alleppey'), (4, 'Kumarakom'), (4, 'Varkala');")

dests = [
    ('Munnar', 'tea', 'Tea hills and misty mornings'), ('Wayanad', 'forest', 'Forests, waterfalls and quiet homestays'),
    ('Alleppey', 'houseboat', 'Backwaters and houseboats'), ('Varkala', 'beach', 'Cliff-top beach town'),
    ('Thekkady', 'forest', 'Spice gardens and Periyar'), ('Kumarakom', 'backwater', 'Lakeside calm on Vembanad'),
    ('Vagamon', 'hills', 'Meadows and pine forests'), ('Kochi', 'villa', 'Heritage, food and the harbour'),
]
for i, (name, img, blurb) in enumerate(dests):
    out.append(f"INSERT INTO destinations (name, slug, image, blurb, popular, sort) VALUES ({q(name)}, {q(name.lower())}, {q('/demo/' + img + '.svg')}, {q(blurb)}, 1, {i});")

CANCEL = 'Free cancellation up to 7 days before check-in. 50% refund 3–7 days before. No refund within 3 days of check-in.'
props = [
    dict(id=1, slug='misty-tea-bungalow-munnar', name='Misty Tea Bungalow', type='homestay', destination='Munnar', lat=10.0889, lng=77.0595,
         address='Chithirapuram, Munnar, Idukki', photos=['tea', 'room', 'hills'], featured=1, family=1, pet=0,
         facilities=['wifi', 'parking', 'hot_water', 'breakfast', 'hill_view', 'campfire', 'power_backup'], meals=['CP', 'MAP'],
         highlights=['Inside a working tea estate', 'Home-cooked Kerala meals', 'Bonfire evenings'],
         desc='A quiet four-room bungalow in the middle of a tea estate, 20 minutes from Munnar town. Wake up to mist over the hills and walk through the plantation with the estate staff.\n\nMeals are home-cooked by the family who run the bungalow — appam, stew and fresh tea from the estate. Good for families and small groups who want a peaceful stay.',
         rooms=[('Estate View Room', 3, 'King + single', 3, 3800, 4500, 2900, 'Breakfast'), ('Family Suite', 5, '2 doubles', 1, 6500, 7500, 5000, 'Breakfast')],
         owner=('Joseph Kurian', '+919847000001'), partner=1, commission=15, rating=(4.7, 0),
         nearby=[('Aluva railway station', 'railway', 110), ('Cochin airport', 'airport', 108), ('Mattupetty Dam', 'attraction', 18), ('Munnar town', 'attraction', 9)],
         rules='Quiet hours after 10pm\nNo loud music\nOutside food allowed'),
    dict(id=2, slug='cloud-nine-villa-munnar', name='Cloud Nine Villa', type='villa', destination='Munnar', lat=10.0700, lng=77.0800,
         address='Pallivasal, Munnar', photos=['villa', 'hills', 'room'], featured=1, family=1, pet=1,
         facilities=['wifi', 'parking', 'kitchen', 'hot_water', 'hill_view', 'power_backup', 'tv'], meals=['EP', 'CP'],
         highlights=['Private 3-bedroom villa', 'Valley-facing deck', 'Pet friendly'],
         desc='A private three-bedroom villa with a wide deck looking over the Pallivasal valley. Full kitchen, a caretaker on call and parking for two cars.\n\nBest for families and groups of friends. The last 600 metres are a steep but paved road.',
         rooms=[('Entire villa (3 bedrooms)', 8, '3 queens + extra mattresses', 1, 14500, 17000, 11000, 'Caretaker, Wi-Fi')],
         owner=('Meera George', '+919847000002'), partner=1, commission=12, rating=(4.5, 0),
         nearby=[('Aluva railway station', 'railway', 105), ('Cochin airport', 'airport', 102), ('Attukad waterfalls', 'attraction', 4)],
         rules='Pets allowed with prior notice\nNo parties after 11pm'),
    dict(id=3, slug='green-canopy-homestay-wayanad', name='Green Canopy Homestay', type='homestay', destination='Wayanad', lat=11.6854, lng=76.1320,
         address='Meppadi, Wayanad', photos=['forest', 'room', 'villa'], featured=1, family=1, pet=0,
         facilities=['wifi', 'parking', 'breakfast', 'garden', 'hot_water', 'campfire', 'ground_floor'], meals=['CP', 'MAP', 'AP'],
         highlights=['Coffee and pepper plantation', 'Ground-floor rooms', 'Guided forest walks'],
         desc='A family-run homestay in a coffee and pepper plantation near Meppadi. Ground-floor rooms open onto the garden, which suits elderly parents and small children.\n\nThe hosts arrange guided walks to Chembra Peak and Soochipara falls.',
         rooms=[('Garden Room', 3, 'Queen + single', 4, 2800, 3300, 2100, 'Breakfast'), ('Family Cottage', 5, '2 queens', 2, 5200, 6000, 4000, 'Breakfast')],
         owner=('Abdul Salam', '+919847000003'), partner=1, commission=15, rating=(4.8, 0),
         nearby=[('Kozhikode railway station', 'railway', 85), ('Calicut airport', 'airport', 95), ('Soochipara falls', 'attraction', 12), ('Chembra Peak', 'attraction', 8)],
         rules='Vegetarian and non-vegetarian food available\nPlease inform dietary needs in advance'),
    dict(id=4, slug='bamboo-treehouse-wayanad', name='Bamboo Treehouse', type='cottage', destination='Wayanad', lat=11.7200, lng=76.0800,
         address='Vythiri, Wayanad', photos=['forest', 'room'], featured=0, family=0, pet=0,
         facilities=['breakfast', 'garden', 'hot_water', 'view', 'campfire'], meals=['CP', 'MAP'],
         highlights=['Treehouse 20 ft up', 'Rainforest sounds', 'Great for couples'],
         desc='Two bamboo treehouses in the Vythiri rainforest, reached by a wooden staircase. Simple, romantic and very quiet. Not suitable for small children or guests who find stairs difficult.',
         rooms=[('Treehouse', 2, 'Double', 2, 6200, 7200, 4800, 'Breakfast, evening tea')],
         owner=('Ravi Das', '+919847000004'), partner=1, commission=18, rating=(4.6, 0),
         nearby=[('Kozhikode railway station', 'railway', 60), ('Pookode lake', 'attraction', 5)],
         rules='Not suitable for children under 10\nNo smoking in the treehouse'),
    dict(id=5, slug='lotus-houseboat-alleppey', name='Lotus Premium Houseboat', type='houseboat', destination='Alleppey', lat=9.4981, lng=76.3388,
         address='Finishing Point, Alleppey', photos=['houseboat', 'backwater', 'room'], featured=1, family=1, pet=0,
         facilities=['ac', 'breakfast', 'lake_view', 'restaurant', 'power_backup'], meals=['AP'],
         highlights=['Overnight backwater cruise', 'All meals on board', 'AC bedrooms'],
         desc='A two-bedroom premium houseboat with air-conditioned rooms and an upper deck. The cruise runs from noon to 5pm through the backwaters, then the boat anchors for the night.\n\nAll meals are cooked on board — Kerala fish curry, karimeen and fresh appam.',
         rooms=[('2-bedroom houseboat', 4, '2 doubles', 3, 9500, 11000, 7500, 'All meals, cruise')],
         owner=('Alleppey Boat Co-op', '+919847000005'), partner=1, commission=10, rating=(4.4, 0),
         nearby=[('Alleppey railway station', 'railway', 4), ('Cochin airport', 'airport', 85), ('Alleppey beach', 'attraction', 5)],
         rules='Check-in 12:00, check-out 09:00\nAC works from 9pm to 6am\nLife jackets on board'),
    dict(id=6, slug='cliff-edge-cottages-varkala', name='Cliff Edge Cottages', type='cottage', destination='Varkala', lat=8.7379, lng=76.7163,
         address='North Cliff, Varkala', photos=['beach', 'room', 'pool'], featured=1, family=1, pet=0,
         facilities=['wifi', 'ac', 'pool', 'sea_view', 'restaurant', 'breakfast'], meals=['EP', 'CP'],
         highlights=['Sea-view cottages on the cliff', 'Pool', '5 minutes to the beach'],
         desc='Six cottages on Varkala North Cliff with a small pool and a café. Sunset views over the Arabian Sea from every veranda.',
         rooms=[('Sea View Cottage', 2, 'Queen', 4, 4800, 5800, 3600, 'Breakfast'), ('Garden Cottage', 3, 'Queen + single', 2, 3600, 4200, 2700, 'Breakfast')],
         owner=('Nikhil Raj', '+919847000006'), partner=1, commission=15, rating=(4.3, 0),
         nearby=[('Varkala Sivagiri railway station', 'railway', 3), ('Trivandrum airport', 'airport', 45), ('Papanasam beach', 'attraction', 1)],
         rules='Pool open 7am–8pm'),
    dict(id=7, slug='spice-garden-retreat-thekkady', name='Spice Garden Retreat', type='resort', destination='Thekkady', lat=9.6031, lng=77.1615,
         address='Kumily, Thekkady', photos=['forest', 'pool', 'room'], featured=1, family=1, pet=0,
         facilities=['wifi', 'parking', 'pool', 'ac', 'restaurant', 'spa', 'garden', 'wheelchair'], meals=['CP', 'MAP', 'AP'],
         highlights=['Spice plantation tours', 'Ayurvedic spa', '2 km from Periyar'],
         desc='A 20-room resort inside a cardamom and pepper garden, two kilometres from the Periyar Tiger Reserve. Pool, Ayurvedic spa and a multi-cuisine restaurant. Wheelchair-friendly paths and lift.',
         rooms=[('Deluxe Room', 3, 'King', 12, 5500, 6500, 4200, 'Breakfast'), ('Pool Villa', 4, 'King + sofa bed', 4, 11000, 13000, 8500, 'Breakfast, spa discount')],
         owner=('Spice Garden Hotels', '+919847000007'), partner=1, commission=18, rating=(4.5, 0),
         nearby=[('Kottayam railway station', 'railway', 110), ('Madurai airport', 'airport', 140), ('Periyar Tiger Reserve', 'attraction', 2)],
         rules='Pool open 7am–7pm\nSpa bookings at reception'),
    dict(id=8, slug='lakeside-heritage-kumarakom', name='Lakeside Heritage Home', type='villa', destination='Kumarakom', lat=9.6175, lng=76.4301,
         address='Kumarakom, Kottayam', photos=['backwater', 'villa', 'room'], featured=0, family=1, pet=1,
         facilities=['wifi', 'ac', 'lake_view', 'kitchen', 'garden', 'parking', 'ground_floor'], meals=['CP', 'MAP'],
         highlights=['100-year-old tharavad', 'Private lake front', 'Canoe rides'],
         desc='A restored 100-year-old Kerala tharavad on the Vembanad lake, with its own jetty and country canoe. Four bedrooms around a central courtyard, all on the ground floor.',
         rooms=[('Heritage Bedroom', 2, 'Queen', 4, 5200, 6000, 4000, 'Breakfast, canoe ride')],
         owner=('Thomas Chacko', '+919847000008'), partner=0, commission=0, rating=(4.9, 0),
         nearby=[('Kottayam railway station', 'railway', 14), ('Cochin airport', 'airport', 90), ('Kumarakom bird sanctuary', 'attraction', 3)],
         rules='Pets allowed\nCanoe rides with life jackets only'),
    dict(id=9, slug='pine-meadow-cottages-vagamon', name='Pine Meadow Cottages', type='cottage', destination='Vagamon', lat=9.6864, lng=76.9050,
         address='Vagamon, Idukki', photos=['hills', 'room'], featured=0, family=1, pet=1,
         facilities=['parking', 'hot_water', 'campfire', 'hill_view', 'breakfast'], meals=['CP', 'MAP'],
         highlights=['Budget-friendly', 'Walk to the meadows', 'Bonfire nights'],
         desc='Simple wooden cottages near the Vagamon meadows and pine forest. Budget-friendly, clean and quiet, with bonfire evenings and Kerala breakfast.',
         rooms=[('Wooden Cottage', 3, 'Double + single', 5, 2400, 2900, 1800, 'Breakfast')],
         owner=('Sajan Mathew', '+919847000009'), partner=1, commission=15, rating=(4.1, 0),
         nearby=[('Kottayam railway station', 'railway', 65), ('Vagamon meadows', 'attraction', 2), ('Pine forest', 'attraction', 4)],
         rules='Quiet after 10pm'),
    dict(id=10, slug='fort-kochi-heritage-stay', name='Fort Kochi Heritage Stay', type='homestay', destination='Kochi', lat=9.9658, lng=76.2421,
         address='Princess Street, Fort Kochi', photos=['villa', 'room'], featured=0, family=1, pet=0,
         facilities=['wifi', 'ac', 'breakfast', 'tv'], meals=['CP'],
         highlights=['Walk to Chinese fishing nets', 'Portuguese-era house', 'Great cafés nearby'],
         desc='A Portuguese-era house in the heart of Fort Kochi, a short walk from the Chinese fishing nets, Jew Town and the best cafés.',
         rooms=[('Heritage Room', 2, 'Queen', 5, 3200, 3800, 2400, 'Breakfast')],
         owner=('Maria Fernandez', '+919847000010'), partner=1, commission=15, rating=(4.2, 0),
         nearby=[('Ernakulam Junction', 'railway', 12), ('Cochin airport', 'airport', 42), ('Chinese fishing nets', 'attraction', 0.5)],
         rules='No smoking indoors'),
]
room_id = 0
room_ids = {}
for p in props:
    nearby = [{'name': n, 'kind': k, 'km': km} for n, k, km in p['nearby']]
    out.append(
        'INSERT INTO properties (id, slug, name, type, destination, address, lat, lng, owner_name, owner_phone, is_partner, commission_pct, highlights, description, facilities, meal_plans, '
        'cancellation_policy, house_rules, nearby, pet_friendly, family_friendly, status, featured, seo_title, seo_description) VALUES ('
        + ', '.join(q(x) for x in [p['id'], p['slug'], p['name'], p['type'], p['destination'], p['address'], p['lat'], p['lng'], p['owner'][0], p['owner'][1], p['partner'], p['commission'],
                                    p['highlights'], p['desc'], p['facilities'], p['meals'], CANCEL, p['rules'], nearby, p['pet'], p['family'], 'live', p['featured'],
                                    f"{p['name']}, {p['destination']} | Go Sanchari", p['desc'][:150]])
        + ');')
    for i, ph in enumerate(p['photos']):
        out.append(f"INSERT INTO property_photos (property_id, r2_key, caption, sort, tags_confirmed) VALUES ({p['id']}, {q('/demo/' + ph + '.svg')}, {q(p['name'])}, {i}, 1);")
    for r in p['rooms']:
        room_id += 1
        room_ids.setdefault(p['id'], []).append(room_id)
        name, cap, bed, units, base, wk, net, inc = r
        out.append(f"INSERT INTO rooms (id, property_id, name, capacity, bed_type, units, base_rate, weekend_rate, net_rate, inclusions, facilities) VALUES ({room_id}, {p['id']}, {q(name)}, {cap}, {q(bed)}, {units}, {base}, {wk}, {net}, {q(inc)}, {q(['hot_water'] + (['ac'] if 'ac' in p['facilities'] else []))});")

# Seasons: Christmas/New Year (+25% everywhere, 3-night minimum) and Onam style fixed example.
out.append("INSERT INTO season_rates (property_id, room_id, name, start_date, end_date, pct_adjust, min_nights) VALUES (NULL, NULL, 'Christmas & New Year', strftime('%Y', 'now') || '-12-20', strftime('%Y', 'now') || '-12-31', 25, 2);")
out.append("INSERT INTO season_rates (property_id, room_id, name, start_date, end_date, rate, min_nights) VALUES (5, NULL, 'Houseboat peak', strftime('%Y', 'now') || '-12-15', strftime('%Y', 'now') || '-12-31', 13500, NULL);")

out.append(f"INSERT INTO coupons (code, title, description, discount_type, discount_value, max_discount, min_amount, valid_from, valid_to, property_ids, usage_limit) VALUES ('WELCOME10', 'Welcome offer', '10% off your first direct booking', 'pct', 10, 2000, 3000, {d(-30)}, {d(120)}, NULL, 500);")
out.append(f"INSERT INTO coupons (code, title, description, discount_type, discount_value, min_amount, valid_from, valid_to, property_ids) VALUES ('MONSOON1500', 'Monsoon in the hills', '₹1,500 off stays of ₹10,000+ in Munnar and Wayanad', 'flat', 1500, 10000, {d(-10)}, {d(60)}, '[1,2,3,4]');")

# Content
faqs = [
    ('How do I pay?', 'You can pay online by UPI, card or net banking. Payments are processed securely by our payment partner. For quotations, you get a payment link on WhatsApp.'),
    ('Is breakfast included?', 'It depends on the property and room. Each room on the property page shows what is included. Breakfast is included where the room says "Includes: Breakfast".'),
    ('What is your cancellation policy?', CANCEL + ' Refunds go back to the original payment method within 5–7 working days.'),
    ('When will I get check-in details?', 'One day before your check-in we send the address, map link and property contact on WhatsApp.'),
    ('Do you arrange taxis or pickups?', 'Yes, we can arrange airport and railway station pickups at extra cost. Ask our team on WhatsApp or mention it in special requests.'),
    ('Are pets allowed?', 'Some properties are pet-friendly — use the "Pet-friendly" filter in search. Please tell us about your pet before booking.'),
    ('What ID do I need?', 'All adult guests need a government photo ID such as Aadhaar, passport, driving licence or voter ID at check-in.'),
    ('What time is check-in and check-out?', 'Usually check-in is from 2pm and check-out is by 11am. Houseboats check in at 12 noon and check out at 9am. Each property page shows its own times.'),
]
out.append(f"INSERT INTO content (key, value) VALUES ('faqs', {q([{'q': a, 'a': b} for a, b in faqs])});")
out.append(f"INSERT INTO content (key, value) VALUES ('about', {q('Go Sanchari is a Kochi-based travel team that personally checks every homestay, villa, resort and houseboat we list across Kerala.' + chr(10) + chr(10) + 'We started in 2019 helping friends find honest, family-friendly stays. Today we work with over 100 property owners, and our team answers every enquiry on WhatsApp — in English and Malayalam.')});")
POLICIES = {
    'cancellation': CANCEL + '\n\nRefunds are approved by our team and sent to the original payment method within 5–7 working days. Date changes are subject to availability and any difference in rates. Houseboat bookings are non-refundable within 7 days of check-in because of weather and crew planning.',
    'privacy': 'We collect your name, phone, email and booking details only to arrange your stay. We share the guest name and phone with the property you booked. We never sell your data. You can ask us to delete your data at any time by emailing hello@gosanchari.com.',
    'terms': "Bookings are confirmed only after payment. Prices include GST as shown at checkout. Guests must follow each property's house rules. Go Sanchari acts as a booking agent for partner properties.",
}
out.append("INSERT INTO content (key, value) VALUES ('policies', " + q(POLICIES) + ");")

# Reviews (approved) + one flagged pending
reviews = [
    (1, 'Rahul Varma', 5, 'Wonderful stay in the middle of the tea estate. The food was amazing and the hosts were so caring. The road is a little bumpy for the last stretch.'),
    (1, 'Sneha Pillai', 4, 'Peaceful and clean. Loved the bonfire. Hot water took time in the morning.'),
    (1, 'David Thomas', 5, 'Best homestay food we had in Kerala. Kids loved the plantation walk.'),
    (3, 'Lakshmi Iyer', 5, 'Ground floor room was perfect for my parents. Very warm hosts and great breakfast.'),
    (3, 'Rahul Varma', 5, 'Quiet, green and the forest walk to Soochipara was the highlight.'),
    (3, 'Sneha Pillai', 4, 'Lovely place, a bit far from town but worth it.'),
    (5, 'David Thomas', 4, 'Great food on the houseboat, sunset was beautiful. AC only at night as mentioned.'),
    (5, 'Rahul Varma', 3, 'Nice cruise but the AC was not working properly for a few hours.'),
    (5, 'Sneha Pillai', 3, 'Food was great but AC was not working in our room for part of the night.'),
    (7, 'Lakshmi Iyer', 5, 'Spa was excellent and the pool villa was huge. Staff very helpful.'),
    (8, 'David Thomas', 5, 'Magical old house on the lake. The canoe ride at sunrise was unforgettable.'),
    (6, 'Sneha Pillai', 4, 'Sunset views from the veranda are stunning. Pool is small.'),
    (2, 'Rahul Varma', 5, 'The deck view is incredible. Kitchen well equipped. Steep road, drive carefully.'),
]
for pid, name, rating, body in reviews:
    out.append(f"INSERT INTO reviews (property_id, guest_name, rating, body, status, created_at) VALUES ({pid}, {q(name)}, {rating}, {q(body)}, 'approved', {ts(-20)});")
out.append(f"INSERT INTO reviews (property_id, guest_name, rating, body, status, flagged, flag_reason, created_at) VALUES (9, 'Promo Bot', 1, 'Cheap rooms here!!! call 9999999999 www.example-spam.com', 'pending', 1, 'Contains contact details or links', {ts(-1)});")
out.append("UPDATE properties SET rating_avg = COALESCE((SELECT AVG(rating) FROM reviews r WHERE r.property_id = properties.id AND r.status = 'approved'), 0), rating_count = (SELECT COUNT(*) FROM reviews r WHERE r.property_id = properties.id AND r.status = 'approved');")
out.append("UPDATE properties SET review_summary = 'Guests love the home-cooked food and tea-estate views; some mention a bumpy last stretch of road.', review_summary_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = 1;")

# Enquiries
enqs = [
    (1, 'GS-ENQ-DEMO01', 10, 'Rahul Varma', '+919812345601', 'Munnar', None, 12, 14, 3, 2, 15000, 'Family of 5 with my elderly parents. Need a ground floor room please, and vegetarian food.', 'website', 'quoted', 3, ['family', 'elderly'], 'Family of 5 (3 adults, 2 kids), Munnar, ₹15k budget, needs ground floor for elderly parents, vegetarian.', -30, -26),
    (2, 'GS-ENQ-DEMO02', 11, 'Sneha Pillai', '+919812345602', 'Alleppey', 5, 20, 21, 2, 0, 12000, 'Honeymoon trip, want a premium houseboat with AC.', 'whatsapp', 'in_progress', 4, ['honeymoon'], 'Couple on honeymoon, Alleppey houseboat, 1 night, ₹12k budget, wants AC.', -5, -3),
    (3, 'GS-ENQ-DEMO03', 12, 'Fathima Rasheed', '+919812345603', 'Wayanad', None, 4, 6, 6, 4, 25000, 'ഞങ്ങൾ 10 പേരുണ്ട്, വയനാട്ടിൽ ഒരു ഹോംസ്റ്റേ വേണം.', 'whatsapp', 'new', None, ['group', 'family', 'urgent'], 'Group of 10 (6 adults, 4 children), Wayanad, ₹25k budget, wants a homestay soon.', -2.5, None),
    (4, 'GS-ENQ-DEMO04', 13, 'David Thomas', '+919812345604', 'Varkala', None, 30, 33, 2, 0, None, 'Looking for a sea view cottage in Varkala.', 'instagram', 'lost', 3, [], 'Couple, Varkala, 3 nights, sea view.', -20, -19),
]
for (eid, code, uid, name, phone, dest, pid, ci, co, ad, ch, budget, msg, src, status, staff, tags, summary, created, staff_reply) in enqs:
    lost = 'Price too high' if status == 'lost' else None
    waiting = 'guest' if staff_reply is not None and status != 'new' else 'us'
    out.append(
        'INSERT INTO enquiries (id, code, user_id, guest_name, phone, destination, property_id, check_in, check_out, adults, children, budget, message, source, status, lost_reason, assigned_to, tags, language, summary, waiting_on, last_guest_msg_at, last_staff_reply_at, first_response_at, created_at, updated_at) VALUES ('
        + ', '.join([q(eid), q(code), q(uid), q(name), q(phone), q(dest), q(pid), d(ci), d(co), q(ad), q(ch), q(budget), q(msg), q(src), q(status), q(lost), q(staff), q(tags), q('ml' if eid == 3 else 'en'), q(summary), q(waiting),
                     ts(created), ts(staff_reply) if staff_reply is not None else 'NULL', ts(staff_reply) if staff_reply is not None else 'NULL', ts(created), ts(staff_reply if staff_reply is not None else created)])
        + ');')
    out.append(f"INSERT INTO messages (enquiry_id, sender, channel, body, created_at) VALUES ({eid}, 'guest', {q('whatsapp' if src == 'whatsapp' else 'website')}, {q(msg)}, {ts(created)});")
    if staff_reply is not None:
        out.append(f"INSERT INTO messages (enquiry_id, sender, user_id, channel, body, created_at) VALUES ({eid}, 'staff', {staff}, 'whatsapp', {q(f'Hi {name.split()[0]}, thanks for reaching out! Let me check the best options for you.')}, {ts(staff_reply)});")
out.append(f"INSERT INTO messages (enquiry_id, sender, channel, body, created_at) VALUES (2, 'guest', 'whatsapp', 'Is dinner included on the houseboat? And can we get a cake for our anniversary?', {ts(-1)});")
out.append(f"UPDATE enquiries SET waiting_on = 'us', last_guest_msg_at = {ts(-1)} WHERE id = 2;")
out.append("INSERT INTO guest_notes (user_id, phone, note, kind, source) VALUES (10, '+919812345601', 'vegetarian', 'preference', 'ai'), (10, '+919812345601', 'travels with elderly parents', 'preference', 'ai'), (11, '+919812345602', 'prefers AC rooms', 'preference', 'staff');")

# Quotation for enquiry 1 (sent, viewed 3 times). Quotes are price snapshots: 2 nights × 2 Estate View Rooms at the base rate + 5% GST.
out.append(f"INSERT INTO quotations (id, code, token, enquiry_id, user_id, staff_id, guest_name, phone, email, status, valid_till, inclusions, payment_terms, message, explainer, view_count, last_viewed_at, sent_at, created_at) VALUES (1, 'GS-QT-DEMO01', 'demo-quote-token-1234567890', 1, 10, 3, 'Rahul Varma', '+919812345601', 'rahul@example.com', 'viewed', {d(2)}, 'Breakfast\nGST', 'Full payment to confirm the booking.', 'Hi Rahul, here is a lovely option for your family in Munnar — two rooms with breakfast.', '2 nights at Misty Tea Bungalow for 5 people in 2 Estate View Rooms, breakfast included, ₹15,960 total.', 3, {ts(-0.5)}, {ts(-1.5)}, {ts(-2)});")
out.append(f"INSERT INTO quotation_options (quotation_id, property_id, room_id, check_in, check_out, adults, children, rooms_count, meal_plan, subtotal, discount, taxes, total) VALUES (1, 1, {room_ids[1][0]}, {d(12)}, {d(14)}, 3, 2, 2, 'CP', 15200, 0, 760, 15960);")
out.append(f"INSERT INTO tasks (assigned_to, enquiry_id, quotation_id, guest_user_id, guest_name, phone, reason, due_at, draft_message) VALUES (3, 1, 1, 10, 'Rahul Varma', '+919812345601', 'Follow up on quote GS-QT-DEMO01 (viewed 3×)', {ts(-0.1)}, 'Hi Rahul, just checking if you had a chance to look at the Munnar options. Happy to hold the rooms for you!');")

# Bookings: one upcoming (tomorrow check-in), one completed with payment, one in stay.
def booking(bid, code, uid, pid, rid, ci, co, nights, adults, children, subtotal, total, taxes, status, pstatus, paid, name, phone, staff, created):
    out.append(
        'INSERT INTO bookings (id, code, user_id, property_id, room_id, check_in, check_out, nights, adults, children, rooms_count, subtotal, taxes, total, amount_paid, status, payment_status, source, guest_name, guest_phone, staff_id, created_at) VALUES ('
        + ', '.join([q(bid), q(code), q(uid), q(pid), q(rid), d(ci), d(co), q(nights), q(adults), q(children), '1', q(subtotal), q(taxes), q(total), q(paid), q(status), q(pstatus), q('website' if staff is None else 'quotation'), q(name), q(phone), q(staff), ts(created)])
        + ');')
    if paid:
        out.append(f"INSERT INTO payments (booking_id, amount, status, gateway, gateway_order_id, gateway_payment_id, created_at, updated_at) VALUES ({bid}, {paid}, 'paid', 'simulator', 'sim_order_seed_{bid}', 'sim_pay_seed_{bid}', {ts(created)}, {ts(created)});")

booking(1, 'GS-BK-DEMO01', 13, 8, room_ids[8][0], 1, 3, 2, 2, 0, 10400, 10920, 520, 'confirmed', 'paid', 10920, 'David Thomas', '+919812345604', None, -10)
booking(2, 'GS-BK-DEMO02', 14, 3, room_ids[3][0], -6, -3, 3, 2, 1, 8400, 8820, 420, 'completed', 'paid', 8820, 'Lakshmi Iyer', '+919812345605', 4, -25)
booking(3, 'GS-BK-DEMO03', 11, 7, room_ids[7][0], -1, 2, 3, 2, 0, 16500, 17325, 825, 'checked_in', 'paid', 17325, 'Sneha Pillai', '+919812345602', 3, -15)
out.append("INSERT INTO payouts (property_id, booking_id, amount, status) VALUES (3, 2, 7140, 'pending'), (7, 3, 13530, 'pending');")

out.append("INSERT INTO activity_log (user_id, action, entity, entity_id, details) VALUES (1, 'seed.loaded', 'system', NULL, '{\"note\":\"Demo data loaded\"}');")
out.append('PRAGMA foreign_keys = ON;')

path = os.path.join(os.path.dirname(__file__), 'seed.sql')
with open(path, 'w') as f:
    f.write('\n'.join(out) + '\n')
print(f'Wrote {path} ({len(out)} statements). Demo staff password: {PASSWORD}')
